# Generated by Django 4.2.5 on 2023-10-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_pedidosexames'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposExames',
            new_name='TiposExame',
        ),
    ]
